apiVersion: v1
kind: Service
metadata:
  labels:
    app: router-service
  name: router-service
  namespace: druid
spec:
  type: NodePort
  ports:
    - name: http
      port: 8088
      protocol: TCP
      targetPort: 8088
      nodePort: 30020
  selector:
    app: druid
    component: router
